# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358db8fc8398fbbaca8efe76a057297c07fa41bc8b157b5adc64dd91fd4b2b1a72553cc52ce8c5b78b013538014be8adef96a67465ef8e5cc8553023b7d68f52

test:
  secret_key_base: e36d9c243fc1f553348fb0be4913477593c0e80e4829032844cce41397b8fc96f25afbf47438fdbc77fc492c4c9f3ad73f2bb9552a4fb4ea6ca2a23d5bf8564f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
